language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before-install:
  - composer install
  - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
